CREATE TABLE `domain` (
                          `id` int(11) NOT NULL,
                          `img` varchar(200) DEFAULT NULL COMMENT 'img-upload',
                          `sort` int(10) UNSIGNED NOT NULL DEFAULT 0,
                          `name` varchar(300) NOT NULL,
                          `fsys_check` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'load-createDomainFolder',
                          `fsys_file` varchar(150) DEFAULT NULL COMMENT 'readonly',
                          `status` tinyint(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'selectG-status',
                          `created` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'readonly',
                          `title` varchar(200) DEFAULT NULL,
                          `description` text DEFAULT NULL,
                          `platform` enum('php','react') DEFAULT NULL,
                          `zone_file` varchar(150) DEFAULT NULL COMMENT 'readonly',
                          `zone_check` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'exe-createZone',
                          `nginx_file` varchar(150) DEFAULT NULL COMMENT 'readonly',
                          `nginx_check` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'exe-createNginx',
                          `maria` varchar(200) DEFAULT NULL,
                          `maria_file` varchar(150) DEFAULT NULL COMMENT 'readonly',
                          `maria_check` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'exe-createMaria',
                          `ssl_file` varchar(150) DEFAULT NULL COMMENT 'readonly',
                          `ssl_expires` datetime DEFAULT NULL COMMENT 'readonly',
                          `ssl_check` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'exe-createSSL',
                          `doc` longtext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
