FROM debian:latest

# Install necessary tools
RUN apt update -y && apt upgrade -y \
    && apt install -y curl wget sudo gnupg2 lsb-release unzip ca-certificates \
    && apt install -y php8.2 php8.2-fpm php8.2-mysql php8.2-bz2 php8.2-redis php8.2-zip \
    && apt install -y mariadb-server mariadb-client \
    && apt install -y nodejs npm \
    && curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && apt-get install -y yarn \
    && apt install -y git

# Copy the install.sh script into the container
COPY install.sh /usr/local/bin/install.sh

# Make sure install.sh is executable
RUN chmod +x /usr/local/bin/install.sh

# Set environment variables (if required)
ENV DOMAIN=example.com

# Run the install.sh script when the container starts
ENTRYPOINT ["./install.sh"]
